blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('entries.urls')),
    path('users/', include('users.urls')),
]

entries/urls.py
from django.urls import path
from .views import HomeView, EntryView, CreateEntryView

app_name = 'entries'

urlpatterns = [
    path('', HomeView.as_view(), name='blog-home'),
    path('entry/<int:pk>/', EntryView.as_view(), name='entry-detail'),
    path('create_entry/', CreateEntryView.as_view(success_url='/'),
         name='create-entry'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

entries/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Entry(models.Model):
    entry_title = models.CharField(max_length=500)
    entry_text = models.TextField()
    entry_date = models.DateTimeField(auto_now_add=True)
    entry_author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.entry_title

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

entries/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView
from .models import Entry

# Create your views here.


class HomeView(LoginRequiredMixin, ListView):
    model = Entry
    template_name = 'entries/index.html'
    context_object_name = 'blog_entries'
    ordering = ['-entry_date']
    paginate_by = 2


class EntryView(LoginRequiredMixin, DetailView):
    model = Entry
    template_name = 'entries/entry_detail.html'


class CreateEntryView(LoginRequiredMixin, CreateView):
    model = Entry
    template_name = 'entries/create_entry.html'
    fields = ['entry_title', 'entry_text']

    def form_valid(self, form):
        form.instance.entry_author = self.request.user
        return super().form_valid(form)

users/views.py
from django.shortcuts import render
from .forms import RegistrationForm
# Create your views here.


def register(request):

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = RegistrationForm()

    context = {'form': form}
    return render(request, 'users/register.html', context)

entries/templates/entries/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blog</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'entries/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'entries/css/blog-home.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'entries:blog-home' %}">My Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'entries:create-entry' %}">Post Now</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      {% block content %}{% endblock %}

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header text-center">Logged in Information</h5>
          <div class="card-body">
            <ul class="list-unstyled mb-0">
              <li>
                <p> <strong>Username:</strong> {{ user.username }} </p>
              </li>
              <li>
                <p> <strong>Email:</strong> {{ user.email }}</p>
              </li>
            </ul>
          </div>
        </div>


      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'entries/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'entries/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

entries/templates/entries/create_entry.html
{% extends "entries/base.html" %}

{% block content %}
<!-- Blog Entries Column -->
<div class="col-md-8">
    <div class="card mb-4 mt-4">
        <div class="card-header">
            Create Blog Post
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Create Post</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

entries/templates/entries/entry_detail.html
{% extends "entries/base.html" %}

{% block content %}
<!-- Blog Entries Column -->
<div class="col-md-8">

    <a href="{% url 'entries:blog-home' %}">Back to home</a>

    <!-- Blog Post -->
    <div class="card mb-4 mt-4">
        <div class="card-body">
            <h3 class="card-title">{{ entry.entry_title }}</h3>
            <p class="card-text">{{ entry.entry_text | linebreaks }}</p>
            <a href="#" class="btn btn-primary btn-sm">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
            Posted on {{ entry.entry_date }} by
            <span class="text-info mr-2">{{ entry.entry_author | capfirst }}</span>
        </div>
    </div>

</div>
{% endblock %}

entries/templates/entries/index.html
{% extends "entries/base.html" %}

{% block content %}
<!-- Blog Entries Column -->
<div class="col-md-8">

    {% for entry in blog_entries %}
    <!-- Blog Post -->
    <div class="card mb-4 mt-4">
        <div class="card-body">
            <h3 class="card-title">{{ entry.entry_title }}</h3>
            <p class="card-text">{{ entry.entry_text | truncatechars:100 }}</p>
            <a href="{% url 'entries:entry-detail' entry.pk %}" class="btn btn-primary btn-sm">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
            Posted on {{ entry.entry_date }} by
            <span class="text-info mr-2">{{ entry.entry_author | capfirst }}</span>
        </div>
    </div>
    {% endfor %}

    {% if is_paginated %}
    <!-- Pagination -->
    <ul class="pagination justify-content-center mb-4">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; Previous Page</a>
        </li>
        {% endif %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next Page &rarr;</a>
        </li>
        {% endif %}
    </ul>
    {% endif %}

</div>
{% endblock %}

users/templates/users/login.html
{% extends "entries/base.html" %}

{% block content %}
<!-- Blog Entries Column -->
<div class="col-md-8">
    <div class="card mb-4 mt-4">
        <div class="card-header">
            Login to your Account
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends "entries/base.html" %}

{% block content %}
<!-- Blog Entries Column -->
<div class="col-md-8">
    <h3>You have successfully logged out.<a href="{% url 'login' %}">Click here to login</a></h3>
</div>
{% endblock %}

users/templates/users/register.html
{% extends "entries/base.html" %}

{% block content %}
<!-- Blog Entries Column -->
<div class="col-md-8">
    <div class="card mb-4 mt-4">
        <div class="card-header">
            Create a Account
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Create Account</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}